blueprint:
  name: " Notificaci贸n de pron贸stico del tiempo "
  description: Env铆e una notificaci贸n personalizable del pron贸stico del tiempo de
    hoy y ma帽ana.
  domain: automation
  input:
    weather_entity:
      name: Entidad meteorol贸gica
      description: La integraci贸n meteorol贸gica que utilizas.
      selector:
        entity:
          filter:
          - domain:
            - weather
          multiple: false
    notify_device:
      name: Dispositivo para notificar
      description: El dispositivo debe ejecutar la aplicaci贸n complementaria oficial
        Home Assistant para recibir notificaciones
      selector:
        device:
          multiple: true
          integration: mobile_app
    time:
      name: Disparador de tiempo
      description: El tiempo para activar la automatizaci贸n y enviar la notificaci贸n.
      selector:
        time: {}
    notification_title:
      name: T铆tulo de la notificaci贸n (opcional)
      description: El t铆tulo de la notificaci贸n.
      default: Pron贸stico del tiempo
    notify_message:
      name: Notificaci贸n del tiempo de hoy
      description: 'Un ejemplo de c贸mo se mostrar谩 el clima. Las unidades configuradas
        en su clima se utilizar谩 la integraci贸n.


        Tiempo: Lluvia torrencial

        Temp: 8.4 // 4.0 掳C

        Precipitaci贸n: 8.6 mm

        Velocidad del viento: 24.1 km/h // Direcci贸n del viento: 273'
      default: Condici贸n
      selector:
        select:
          mode: list
          multiple: true
          options:
          - label: Tiempo
            value: condition
          - label: Temperatura
            value: temperature
          - label: Precipitaci贸n
            value: precipitation
          - label: Viento
            value: wind
          sort: false
          custom_value: false
    tomorrow_message:
      name: Notificaci贸n del tiempo de ma帽ana
      description: 'Un ejemplo de c贸mo se mostrar谩 el clima. Las unidades configuradas
        en su clima se utilizar谩 la integraci贸n.


        Ma帽ana: Lluvioso, Temperatura: 13.2 // 11.7 掳C, Precipitaci贸n: 2.5 mm'
      default: tomorrow
      selector:
        select:
          mode: dropdown
          options:
          - label: S铆, env铆a informaci贸n sobre el tiempo de ma帽ana
            value: tomorrow
          - label: No, no env铆es informaci贸n sobre el tiempo de ma帽ana
            value: noTomorrow
          multiple: false
          sort: false
          custom_value: false
  source_url: https://github.com/cvc90/HA-Blueprints/blob/main/Scripts/notificacion_meteorologica.yaml
variables:
  notify_device: !input notify_device
  weather_entity: !input weather_entity
  notification_title: !input notification_title
  time: !input time
  device_id: !input notify_device
  notify_message: !input notify_message
  tomorrow_message: !input tomorrow_message
trigger:
  platform: time
  at: !input time
action:
- service: weather.get_forecasts
  data:
    type: daily
  target:
    entity_id: !input weather_entity
  response_variable: daily
- variables:
    weather_entity: !input weather_entity
    forecast: '{{ daily[weather_entity].forecast }}'
    icon: '{% set cond_now = forecast[0].condition %}{% if cond_now == ''cloudy''
      %}mdi:clouds{% elif cond_now == ''fog'' %}mdi:weather-fog{% elif cond_now ==
      ''hail'' %}mdi:weather-hail{% elif cond_now == ''lightning'' %}mdi:weather-lightning{%
      elif cond_now == ''lightning-rainy'' %}mdi:weather-lightning-rainy{% elif cond_now
      == ''partlycloudy'' %}mdi:weather-partly-cloudy{% elif cond_now == ''pouring''
      %}mdi:weather-pouring{% elif cond_now == ''rainy'' %}mdi:weather-rainy{% elif
      cond_now == ''snowy'' %}mdi:weather-snowy{% elif cond_now == ''snowy-rainy''
      %}mdi:weather-snowy-rainy{% elif cond_now == ''sunny'' %}mdi:weather-sunny{%
      elif cond_now == ''windy'' %}mdi:weather-windy{% elif cond_now == ''windy-variant''
      %}mdi:weather-windy-variant{% elif cond_now == ''exceptional'' %}mdi:cloud-alert{%
      else %}mdi:sun-thermometer{% endif %}'
- repeat:
    for_each: !input notify_device
    sequence:
    - service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}
      data:
        title: '{{ notification_title }}'
        message: "{% set weather = weather_entity %}
          {% set condition_translations = {
              'clear-night': 'Noche despejada',
              'cloudy': 'Nublado',
              'fog': 'Niebla',
              'hail': 'Granizo',
              'lightning': 'Rel谩mpagos',
              'lightning-rainy': 'Rel谩mpagos y lluvia',
              'partlycloudy': 'Parcialmente nublado',
              'pouring': 'Lluvia torrencial',
              'rainy': 'Lluvioso',
              'snowy': 'Nevando',
              'snowy-rainy': 'Nieve y lluvia',
              'sunny': 'Soleado',
              'windy': 'Ventoso',
              'windy-variant': 'Ventoso variable',
              'exceptional': 'Excepcional'
          } %}                     
          {% for message in notify_message
          %}\n  {% if \"condition\" in message %}Tiempo: {{ state_translated(weather_entity)
          }}{% endif %}{% if \"temperature\" in message %}Temp: {{forecast[0].temperature}}
          // {{forecast[0].templow}} {{ state_attr(weather,'temperature_unit') }}{%
          endif %}{% if \"precipitation\" in message %}Precipitaci贸n: {{forecast[0].precipitation}}
          {{ state_attr(weather,'precipitation_unit') }}{% endif %}{% if \"wind\"
          in message %}Velocidad del viento: {{forecast[0].wind_speed}} {{ state_attr(weather,'wind_speed_unit')
          }} // Direcci贸n del viento: {{forecast[0].wind_bearing}}{% endif %}\n{% endfor %}\n{%if
          tomorrow_message == 'tomorrow' %}Ma帽ana: {{ condition_translations.get(forecast[1].condition, forecast[1].condition) | capitalize 
          }}, Temp: {{forecast[1].temperature}} // {{forecast[1].templow}} {{ state_attr(weather,'temperature_unit')
          }}, Precipitaci贸n: {{forecast[1].precipitation}} {{ state_attr(weather,'precipitation_unit')
          }} {%endif%}"
        data:
          notification_icon: '{{ icon }}'
